-- Add new columns to agents table for CRUD, tools, knowledge bases, sharing
ALTER TABLE agents ADD COLUMN IF NOT EXISTS provider TEXT DEFAULT 'anthropic';
ALTER TABLE agents ADD COLUMN IF NOT EXISTS temperature NUMERIC(3,2) DEFAULT 0.0;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS timeout_seconds INTEGER DEFAULT 120;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS max_retries INTEGER DEFAULT 3;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS max_tokens INTEGER DEFAULT 4096;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS tools JSONB DEFAULT '[]';
ALTER TABLE agents ADD COLUMN IF NOT EXISTS knowledge_bases JSONB DEFAULT '[]';
ALTER TABLE agents ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT false;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '[]';
